-- SET client_encoding TO 'UTF8';   
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Baahubali: The Beginning', 'movie', 'In the ancient kingdom of Mahishmati, a daring young man named Shivudu uncovers his royal legacy as the son of the legendary warrior Amarendra Baahubali. As he learns about his father''s heroic deeds and tragic betrayal by his own brother Bhallaladeva, Shivudu must reclaim his rightful throne in this epic tale of courage, love, and betrayal that features breathtaking action sequences and stunning visual effects.', '2015-07-10', ARRAY['Action', 'Adventure', 'Drama'], 'PG-13', 'Telugu', 159, 'S. S. Rajamouli', ARRAY['Prabhas', 'Rana Daggubati', 'Anushka Shetty', 'Tamannaah', 'Ramya Krishnan'], ARRAY['Netflix', 'Amazon Prime'], 'https://youtu.be/sOEg_YZQsTI', 'https://i.pinimg.com/736x/36/44/3d/36443dc099d96078744a1d4de9863787.jpg', NULL),
('Baahubali 2: The Conclusion', 'movie', 'The dramatic conclusion to the Baahubali saga reveals why Kattappa killed Amarendra Baahubali while following Mahendra Baahubali''s quest to avenge his father''s death and reclaim the Mahishmati kingdom from the tyrannical rule of Bhallaladeva. This visually spectacular finale features even grander battles, emotional reunions, and answers to all the mysteries set up in the first film.', '2017-04-28', ARRAY['Action', 'Fantasy'], 'PG-13', 'Telugu', 171, 'S. S. Rajamouli', ARRAY['Prabhas', 'Anushka Shetty', 'Rana Daggubati', 'Tamannaah', 'Ramya Krishnan'], ARRAY['Netflix'], 'https://youtu.be/G62HrubdD6o', 'https://www.themoviedb.org/t/p/w1280/xQ22LOWSkClP3maYhR9nZH0dnWM.jpg', NULL),
('Pushpa: The Rise', 'movie', 'Pushpa Raj, a humble lorry driver working for red sandalwood smugglers in the Seshachalam forests, rises through the ranks of the illegal smuggling syndicate through his intelligence, ruthlessness, and ambition. As he challenges the existing power structures and makes powerful enemies, Pushpa must navigate treacherous alliances in this gritty action drama featuring Allu Arjun''s iconic performance and memorable dialogues.', '2021-12-17', ARRAY['Action', 'Drama'], 'PG-13', 'Telugu', 179, 'Sukumar', ARRAY['Allu Arjun', 'Rashmika Mandanna', 'Fahadh Faasil'], ARRAY['Amazon Prime'], 'https://youtu.be/Q1NKMPhP8PY', 'https://www.themoviedb.org/t/p/w1280/r1yAzVQNbCbPTbB3GZFour9Qr0t.jpg', NULL),
('Arjun Reddy', 'movie', 'Arjun Reddy, a brilliant but self-destructive surgeon, spirals into alcoholism and drug abuse when his girlfriend Preeti is forced to marry someone else. This raw and intense romantic drama explores toxic masculinity, obsessive love, and redemption as Arjun hits rock bottom before attempting to rebuild his life. The film sparked controversy for its portrayal of relationships but gained cult status for its uncompromising vision.', '2017-08-25', ARRAY['Drama', 'Romance'], 'A', 'Telugu', 182, 'Sandeep Reddy Vanga', ARRAY['Vijay Deverakonda', 'Shalini Pandey'], ARRAY['Aha', 'Amazon Prime'], 'https://youtu.be/aozErFqz3gU', 'https://www.themoviedb.org/t/p/w1280/u9yryEQRGJYobvtneoyeIEhuCUj.jpg', NULL),
('Eega', 'movie', 'After being murdered by a jealous industrialist named Sudeep, Nani is reincarnated as a housefly with retained human memories. The tiny but determined fly wages an inventive and often hilarious one-insect war against his killer to protect the woman he loves. This innovative fantasy film blends live-action with groundbreaking CGI to tell a unique revenge story from a fly''s-eye view.', '2012-07-06', ARRAY['Fantasy', 'Action'], 'U', 'Telugu', 134, 'S. S. Rajamouli', ARRAY['Nani', 'Samantha Ruth Prabhu', 'Sudeep'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/6jVwFf4bH74', 'https://www.themoviedb.org/t/p/w1280/xbCPJejbJgRIuOwUzJqcBUjCbFB.jpg', NULL),
('Mahanati', 'movie', 'This biographical drama chronicles the rise and fall of Savitri, the legendary South Indian actress who ruled the silver screen in the 1950s-60s. From her humble beginnings to becoming the first female superstar of Indian cinema, and her subsequent decline due to personal struggles, the film paints a poignant portrait of fame, love, and tragedy through exquisite period detail and Keerthy Suresh''s award-winning performance.', '2018-05-09', ARRAY['Biography', 'Drama'], 'PG', 'Telugu', 177, 'Nag Ashwin', ARRAY['Keerthy Suresh', 'Dulquer Salmaan', 'Samantha Ruth Prabhu'], ARRAY['Amazon Prime'], 'https://youtu.be/A0Gx78bC-2Q', 'https://www.themoviedb.org/t/p/w1280/5hwtlwoLdSpkoeusT0sf8qW5VFB.jpg', NULL),
('Ala Vaikunthapurramuloo', 'movie', 'Bantu grows up neglected by his father who believes another man''s son is his own due to a hospital mix-up. When Bantu discovers his true parentage and that he''s actually the heir to a wealthy family, he must navigate the complexities of his new position while dealing with family politics, romance, and his doppelgänger. This stylish masala entertainer features Allu Arjun''s electrifying dance moves and a chart-topping soundtrack.', '2020-01-12', ARRAY['Action', 'Comedy', 'Drama'], 'PG', 'Telugu', 165, 'Trivikram Srinivas', ARRAY['Allu Arjun', 'Pooja Hegde', 'Tabu', 'Jayaram'], ARRAY['Netflix'], 'https://youtu.be/QdD3Qd-lLfY', 'https://www.themoviedb.org/t/p/w1280/2rzORJaegE2bbKNVkQXbZCeV0BP.jpg', NULL),
('RRR', 'movie', 'This fictional tale imagines a friendship between two real-life Indian revolutionaries - Alluri Sitarama Raju and Komaram Bheem - during the British Raj. When a British officer kidnaps a tribal girl, Bheem comes to Delhi to rescue her and forms an unlikely bond with Raju, unaware that Raju is working undercover for the British. The film''s spectacular action sequences, emotional depth, and technical brilliance made it a global phenomenon.', '2022-03-25', ARRAY['Action', 'Historical', 'Drama'], 'PG-13', 'Telugu', 182, 'S. S. Rajamouli', ARRAY['N. T. Rama Rao Jr.', 'Ram Charan', 'Alia Bhatt', 'Ajay Devgn'], ARRAY['Netflix'], 'https://youtu.be/f_vbAtFSEc0', 'https://www.themoviedb.org/t/p/w1280/nEufeZlyAOLqO2brrs0yeF1lgXO.jpg', NULL),
('Sita Ramam', 'movie', 'In 1985, an orphaned woman receives letters sent to her by an army officer named Ram in 1964. Through these letters, she uncovers a poignant love story between Lieutenant Ram, stationed in Kashmir, and Sita Mahalakshmi, the princess of a royal family. As their romance blossoms across religious and social divides, political tensions rise, leading to a heartbreaking separation with consequences that echo decades later.', '2022-08-05', ARRAY['Romance', 'Drama'], 'U', 'Telugu', 163, 'Hanu Raghavapudi', ARRAY['Dulquer Salmaan', 'Mrunal Thakur'], ARRAY['Amazon Prime'], 'https://youtu.be/3bomQxDkOaQ', 'https://www.themoviedb.org/t/p/w1280/zcsKp0GvD2qlgn5zOuENJ0lT9UK.jpg', NULL),
('Jersey', 'movie', 'Arjun, a talented but failed cricketer in his late 30s, decides to make a comeback to fulfill his son''s wish for a cricket jersey. As he battles age, financial struggles, and skepticism from everyone around him, Arjun''s journey becomes an emotional testament to second chances and the power of dreams. Nani delivers a career-best performance in this sports drama that celebrates perseverance against all odds.', '2019-04-19', ARRAY['Drama', 'Sport'], 'U', 'Telugu', 157, 'Gowtam Tinnanuri', ARRAY['Nani', 'Shraddha Srinath'], ARRAY['Zee5'], 'https://youtu.be/NaZHM9bxpuI', 'https://www.themoviedb.org/t/p/w1280/bU9q9yVtxeBiC0Do27CekHXNE6D.jpg', NULL),
('3 Idiots', 'movie', 'Two friends embark on a journey to find their long-lost college companion Ranchoddas. Through flashbacks, they recall their days at an elite engineering college where they rebelled against the oppressive system under the guidance of the free-spirited Rancho, whose unconventional wisdom changed their lives. This heartwarming comedy-drama critiques educational pressures while celebrating friendship and pursuing one''s passion.', '2009-12-25', ARRAY['Comedy', 'Drama'], 'PG-13', 'Hindi', 170, 'Rajkumar Hirani', ARRAY['Aamir Khan', 'R. Madhavan', 'Sharman Joshi', 'Kareena Kapoor'], ARRAY['Netflix', 'Amazon Prime'], 'https://youtu.be/K0eDlFX9GMc', 'https://www.themoviedb.org/t/p/w1280/66A9MqXOyVFCssoloscw79z8Tew.jpg', NULL),
('Lagaan', 'movie', 'In 1893, during the British Raj, villagers from Champaner face crippling taxes during a drought. When arrogant officer Captain Russell offers them a impossible wager - beat the British at cricket to waive their taxes for three years - the villagers, led by Bhuvan, must learn the alien sport to save their homes. This epic sports drama blends historical fiction with rousing underdog triumph in a vibrant musical package.', '2001-06-15', ARRAY['Drama', 'Sport'], 'PG', 'Hindi', 224, 'Ashutosh Gowariker', ARRAY['Aamir Khan', 'Gracy Singh', 'Rachel Shelley'], ARRAY['Netflix'], 'https://youtu.be/1dCC0UuUhJk', 'https://www.themoviedb.org/t/p/w1280/yNX9lFRAFeNLNRIXdqZK9gYrYKa.jpg', NULL),
('Swades', 'movie', 'NASA scientist Mohan Bhargava returns to India to find his childhood nanny and is gradually drawn into the struggles of rural life. Witnessing the poverty, caste discrimination, and lack of basic amenities, Mohan undergoes a transformation as he uses his technical skills to bring electricity to a village, discovering his true calling in the process. This thoughtful drama explores patriotism beyond nationalism.', '2004-12-17', ARRAY['Drama'], 'PG', 'Hindi', 210, 'Ashutosh Gowariker', ARRAY['Shah Rukh Khan', 'Gayatri Joshi'], ARRAY['Netflix'], 'https://youtu.be/nkS_Ar0Yad0', 'https://www.themoviedb.org/t/p/w1280/yUSL24kpHc9Nls4Pohia4shgcIM.jpg', NULL),
('Gully Boy', 'movie', 'Inspired by the lives of Mumbai street rappers like Divine and Naezy, this film follows Murad, a young man from the Dharavi slums who channels his frustrations and dreams into rap music. As he navigates family pressures, class struggles, and the underground hip-hop scene, Murad finds his voice and a path to self-expression in this vibrant musical drama that launched India''s rap revolution.', '2019-02-14', ARRAY['Musical', 'Drama'], 'PG-13', 'Hindi', 154, 'Zoya Akhtar', ARRAY['Ranveer Singh', 'Alia Bhatt', 'Siddhant Chaturvedi'], ARRAY['Amazon Prime'], 'https://youtu.be/JfbxcD6biOk', 'https://www.themoviedb.org/t/p/w1280/4RE7TD5TqEXbPKyUHcn7CSeMlrJ.jpg', NULL),
('Kahaani', 'movie', 'Vidya Bagchi, a pregnant woman from London, arrives in Kolkata searching for her missing husband. As she digs deeper into the disappearance with the help of a local cop, she uncovers a web of deception connected to a deadly terrorist attack. This gripping thriller keeps audiences guessing until its shocking climax, with Vidya Balan delivering a powerhouse performance as the determined protagonist.', '2012-03-09', ARRAY['Thriller', 'Mystery'], 'PG-13', 'Hindi', 122, 'Sujoy Ghosh', ARRAY['Vidya Balan', 'Parambrata Chatterjee', 'Nawazuddin Siddiqui'], ARRAY['Netflix'], 'https://youtu.be/j4sIlgcH0-U', 'https://www.themoviedb.org/t/p/w1280/e2eQVOrdQ8k7yYjjHKHP2nlwbTu.jpg', NULL),
('Barfi!', 'movie', 'Murphy "Barfi" Johnson, a charming deaf-mute man in 1970s Darjeeling, forms a deep bond with Shruti, who ultimately chooses conventional security over their unconventional love. Years later, when Barfi reconnects with his autistic childhood friend Jhilmil, their innocent relationship blossoms into something beautiful. This whimsical romance celebrates life''s simple joys and the universal language of love beyond words.', '2012-09-14', ARRAY['Comedy', 'Drama', 'Romance'], 'PG', 'Hindi', 151, 'Anurag Basu', ARRAY['Ranbir Kapoor', 'Priyanka Chopra', 'Ileana DCruz'], ARRAY['Netflix'], 'https://youtu.be/yZxrao3zou4', 'https://www.themoviedb.org/t/p/w1280/3dMcxaL0oD79nc31FQK5D7YZ3Kv.jpg', NULL),
('Queen', 'movie', 'When her fiancé calls off their wedding just days before the ceremony, Rani, a sheltered Delhi girl, decides to go on her planned honeymoon alone. From Paris to Amsterdam, her solo journey becomes a liberating adventure of self-discovery as she befriends fellow travelers, confronts her fears, and learns to embrace life on her own terms in this heartwarming feminist comedy-drama.', '2014-03-07', ARRAY['Adventure', 'Comedy', 'Drama'], 'PG', 'Hindi', 146, 'Vikas Bahl', ARRAY['Kangana Ranaut', 'Rajkummar Rao', 'Lisa Haydon'], ARRAY['Netflix'], 'https://youtu.be/KGC6vl3lzf0', 'https://www.themoviedb.org/t/p/w1280/vKLp0X2RQOuA31R3AdaYtDdKIPK.jpg', NULL),
('Dangal', 'movie', 'Based on the true story of Mahavir Singh Phogat, a former wrestler who trains his daughters Geeta and Babita to become India''s first world-class female wrestlers. Breaking gender stereotypes in rural Haryana, Mahavir''s rigorous coaching and belief in his daughters'' potential leads them to Commonwealth Games glory in a sports drama that combines rousing action with emotional family dynamics.', '2016-12-23', ARRAY['Action', 'Biography', 'Drama'], 'PG', 'Hindi', 161, 'Nitesh Tiwari', ARRAY['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra'], ARRAY['Netflix'], 'https://youtu.be/x_7YlGv9u1g', 'https://www.themoviedb.org/t/p/w1280/lHd3W8E5aKoki9pDP7tN7yEh3c0.jpg', NULL),
('Piku', 'movie', 'Piku Banerjee, a headstrong architect, lives with her hypochondriac father Bhaskor whose eccentricities dominate their lives. When they embark on a road trip from Delhi to Kolkata to visit their ancestral home, accompanied by pragmatic taxi owner Rana, the journey becomes a hilarious and heartwarming exploration of family bonds, generational differences, and letting go.', '2015-05-08', ARRAY['Comedy', 'Drama'], 'PG', 'Hindi', 123, 'Shoojit Sircar', ARRAY['Deepika Padukone', 'Amitabh Bachchan', 'Irrfan Khan'], ARRAY['Amazon Prime'], 'https://youtu.be/oeiKUlUUNQ8', 'https://www.themoviedb.org/t/p/w1280/yo7EZWiLpLGhqs3YnlDGDBPjfTb.jpg', NULL),
('Andhadhun', 'movie', 'Akash, a blind pianist pretending to be visually impaired for artistic inspiration, unwittingly becomes embroiled in the murder of a former film star. As he navigates a web of lies, blackmail, and coincidences, the line between his performance and reality blurs in this darkly comic thriller filled with shocking twists and morally ambiguous characters.', '2018-10-05', ARRAY['Crime', 'Thriller'], 'PG-13', 'Hindi', 139, 'Sriram Raghavan', ARRAY['Ayushmann Khurrana', 'Tabu', 'Radhika Apte'], ARRAY['Netflix'], 'https://youtu.be/2iVYI99VGaw', 'https://www.themoviedb.org/t/p/w1280/dy3K6hNvwE05siGgiLJcEiwgpdO.jpg', NULL),
('Article 15', 'movie', 'IPS officer Ayan Ranjan arrives in rural Uttar Pradesh to investigate the disappearance of three Dalit girls, uncovering deep-rooted caste discrimination and systemic apathy. As he confronts the brutal realities of India''s social hierarchy and police complicity, Ayan must navigate moral dilemmas and bureaucratic hurdles to deliver justice in this hard-hitting political thriller inspired by real incidents.', '2019-06-28', ARRAY['Crime', 'Drama'], 'PG-13', 'Hindi', 130, 'Anubhav Sinha', ARRAY['Ayushmann Khurrana', 'Isha Talwar', 'Manoj Pahwa'], ARRAY['Netflix'], 'https://youtu.be/HKOJY0cMeUQ', 'https://www.themoviedb.org/t/p/w1280/7pCaexxVAq37Q9Rzo3saBP8DOHn.jpg', NULL),
('Drishyam', 'movie', 'Vijay Salgaonkar, a cable operator with a fourth-grade education, becomes embroiled in a high-stakes cat-and-mouse game when his family accidentally kills the son of Inspector General Meera Deshmukh. Using his wits and knowledge gleaned from crime films, Vijay constructs an elaborate alibi in this gripping thriller about how far a father will go to protect his family.', '2015-07-31', ARRAY['Crime', 'Drama', 'Mystery'], 'PG-13', 'Hindi', 163, 'Nishikant Kamat', ARRAY['Ajay Devgn', 'Shriya Saran', 'Tabu'], ARRAY['Amazon Prime'], 'https://youtu.be/AuuX2j14NBg', 'https://www.themoviedb.org/t/p/w1280/gIClWRv5OSe8rl5Koi0AeUcCZ9Z.jpg', NULL),
('Pink', 'movie', 'When three independent women are falsely accused of assaulting a powerful politician''s nephew after a party gone wrong, retired lawyer Deepak Sehgal takes up their case pro bono. This courtroom drama exposes societal prejudices against women''s freedom and consent, delivering a powerful message about equality and the importance of "no means no" in contemporary India.', '2016-09-16', ARRAY['Drama', 'Thriller'], 'PG-13', 'Hindi', 136, 'Aniruddha Roy Chowdhury', ARRAY['Amitabh Bachchan', 'Taapsee Pannu', 'Kirti Kulhari'], ARRAY['Netflix'], 'https://youtu.be/AL2TShb6fFs', 'https://www.themoviedb.org/t/p/w1280/6xNhnyKm2M5FEOY7xv5iKiQ5P3.jpg', NULL);

-- Adding more Nani movies
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Bhale Bhale Magadivoy', 'movie', 'A forgetful scientist with short-term memory loss falls in love but struggles to maintain his relationship due to his condition. This hilarious romantic comedy showcases Nani''s impeccable comic timing as he navigates increasingly absurd situations caused by his memory lapses, culminating in a heartwarming resolution about love overcoming all obstacles.', '2015-09-04', ARRAY['Comedy', 'Romance'], 'U', 'Telugu', 153, 'Maruthi', ARRAY['Nani', 'Lavanya Tripathi'], ARRAY['Amazon Prime'], 'https://youtu.be/2HmGdZ3gF4s', 'https://www.themoviedb.org/t/p/w1280/fa2Nv68gcmgZJbKCJV5T45fwA8P.jpg', NULL),
('Ninnu Kori', 'movie', 'Uma, settled in the US, returns to India to win back his ex-girlfriend Pallavi who is about to marry another man. This emotional romantic drama explores themes of love, sacrifice, and moving on, with Nani delivering a nuanced performance as a man torn between his feelings and doing what''s right for the woman he loves.', '2017-07-07', ARRAY['Drama', 'Romance'], 'U', 'Telugu', 142, 'Shiva Nirvana', ARRAY['Nani', 'Nivetha Thomas', 'Aadhi Pinisetty'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/5I1y5K8XJ5Y', 'https://www.themoviedb.org/t/p/w1280/tSqphL6d7slQ0zFmnhliYE9oyAS.jpg', NULL),
('Gentleman', 'movie', 'A vigilante journalist adopts two identities - a suave businessman and a rugged common man - to expose corruption in the education system. This action thriller showcases Nani''s versatility as he plays dual roles in a cat-and-mouse game with a powerful politician, blending social message with commercial entertainment.', '2016-06-17', ARRAY['Action', 'Thriller'], 'UA', 'Telugu', 147, 'Mohan Krishna Indraganti', ARRAY['Nani', 'Surbhi'], ARRAY['Amazon Prime'], 'https://youtu.be/5I1y5K8XJ5Y', 'https://www.themoviedb.org/t/p/w1280/hoO5BunFOXp5s8WkuRB4SgsruaS.jpg', NULL),
('Shyam Singha Roy', 'movie', 'A young filmmaker begins experiencing visions of a past life as Shyam Singha Roy, a revolutionary poet who fought against social injustice in 1970s Bengal. As he investigates these memories, he uncovers a tragic love story and unfinished mission that he must complete in this reincarnation drama blending period and contemporary narratives.', '2021-12-24', ARRAY['Drama', 'Romance'], 'UA', 'Telugu', 155, 'Rahul Sankrityan', ARRAY['Nani', 'Sai Pallavi', 'Krithi Shetty'], ARRAY['Netflix'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/nUHk72rSGDuG2Lz22zJAYCyxq7g.jpg', NULL),
('Dasara', 'movie', 'Set in a rustic village dominated by liquor and violence, three childhood friends find their bond tested by circumstances beyond their control. This raw and intense drama explores themes of friendship, betrayal, and redemption against the backdrop of rural Telangana''s political and social realities.', '2023-03-30', ARRAY['Action', 'Drama'], 'UA', 'Telugu', 158, 'Srikanth Odela', ARRAY['Nani', 'Keerthy Suresh'], ARRAY['Netflix'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/4OTVoCVXa5aHDZl8opKoIV9Ezr5.jpg', NULL);

-- Adding Ram Charan movies
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Magadheera', 'movie', 'In a tale spanning 400 years, a warrior reincarnates to protect his lover from their past life''s nemesis. This epic fantasy romance established Ram Charan as a leading star, featuring breathtaking action sequences, lavish production design, and a timeless love story that transcends centuries.', '2009-07-31', ARRAY['Action', 'Fantasy', 'Romance'], 'U', 'Telugu', 166, 'S. S. Rajamouli', ARRAY['Ram Charan', 'Kajal Aggarwal'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/aqz-KE-bpKQ', 'https://www.themoviedb.org/t/p/w1280/w9zOKnYXLZOccjn4vjd3EkuVFKX.jpg', NULL),
('Rangasthalam', 'movie', 'Chitti Babu, a partially deaf villager, gets embroiled in his brother''s crusade against a corrupt village president in 1980s Andhra Pradesh. This rustic drama with political undertones features Ram Charan''s career-best performance and authentic period detailing that transports viewers to rural India during economic transition.', '2018-03-30', ARRAY['Drama', 'Action'], 'UA', 'Telugu', 170, 'Sukumar', ARRAY['Ram Charan', 'Samantha Ruth Prabhu'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/yiEzDgBBFC25Zd6z0r7sMngn5vr.jpg', NULL),
('Dhruva', 'movie', 'An upright IPS officer goes undercover to dismantle a powerful criminal syndicate led by a ruthless businessman. This gripping cat-and-mouse thriller showcases Ram Charan in a intense performance as he methodically brings down a seemingly untouchable villain in a battle of wits and willpower.', '2016-12-09', ARRAY['Action', 'Thriller'], 'UA', 'Telugu', 158, 'Surender Reddy', ARRAY['Ram Charan', 'Rakul Preet Singh'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/hh7D1fLjet1Ce1kcCkk5TVr3g9O.jpg', NULL),
('Vinaya Vidheya Rama', 'movie', 'Rama, a protective brother, takes on a powerful politician when his younger brother gets entangled in criminal activities. This action-packed family drama features Ram Charan in a mass avatar with high-octane fight sequences and emotional family moments.', '2019-01-11', ARRAY['Action', 'Drama'], 'UA', 'Telugu', 150, 'Boyapati Srinu', ARRAY['Ram Charan', 'Kiara Advani'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/tOjSnrKwI3qVKMHn5ofwc2K3Sm3.jpg', NULL),
('Yevadu', 'movie', 'A man with a surgically altered face seeks revenge against those who killed his lover while protecting a woman who shares her likeness. This action thriller explores themes of identity, vengeance, and redemption with Ram Charan playing dual roles in a complex narrative of switched faces and hidden agendas.', '2014-01-12', ARRAY['Action', 'Thriller'], 'UA', 'Telugu', 162, 'Vamsi Paidipally', ARRAY['Ram Charan', 'Allu Arjun', 'Shruti Haasan'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/euSAn9sVeS4Qnaj1ZWDw56gPi9W.jpg', NULL);

-- Adding Allu Arjun movies
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Arya', 'movie', 'Arya, an eccentric young man, falls in love with a girl already in a relationship and believes in "love without expectations." This romantic drama established Allu Arjun''s signature style and dancing prowess while presenting an unconventional love story that became a cultural phenomenon in Telugu cinema.', '2004-05-07', ARRAY['Romance', 'Drama'], 'U', 'Telugu', 165, 'Sukumar', ARRAY['Allu Arjun', 'Anu Mehta'], ARRAY['Amazon Prime'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/1RU7eOgierTfTiNNQUmd1h5iKFU.jpg', NULL),
('Race Gurram', 'movie', 'A reckless young man teams up with his police officer brother to take down a powerful crime syndicate. This action-comedy showcases Allu Arjun''s impeccable comic timing and dancing skills in a entertaining package of brotherly bonding and high-stakes action.', '2014-04-11', ARRAY['Action', 'Comedy'], 'U', 'Telugu', 165, 'Surender Reddy', ARRAY['Allu Arjun', 'Shaam'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/4ojbzpHL0wmlnrmlLQGLds6Hwvu.jpg', NULL),
('Sarrainodu', 'movie', 'An ex-military officer takes on a corrupt politician and his empire to protect the common people. This mass entertainer features Allu Arjun in a powerful action avatar with high-energy dance numbers and gravity-defying fight sequences that became fan favorites.', '2016-04-22', ARRAY['Action', 'Drama'], 'UA', 'Telugu', 158, 'Boyapati Srinu', ARRAY['Allu Arjun', 'Rakul Preet Singh'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/olXLUc36dmYFdZrU7UkC3DeADfv.jpg', NULL),
('DJ: Duvvada Jagannadham', 'movie', 'A traditional Brahmin caterer leads a double life as a vigilante who punishes corrupt officials. This stylish action film blends Allu Arjun''s dancing prowess with high-octane action sequences and a unique character dichotomy that showcases his versatility.', '2017-06-23', ARRAY['Action', 'Comedy'], 'UA', 'Telugu', 150, 'Harish Shankar', ARRAY['Allu Arjun', 'Pooja Hegde'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/71aRdJ1BVKXiwaERnD2UWL3J5AR.jpg', NULL),
('Naa Peru Surya', 'movie', 'A short-tempered army officer undergoes anger management training while confronting his past demons. This action drama explores themes of anger, redemption, and patriotism with Allu Arjun delivering a physically demanding performance as the volatile protagonist.', '2018-05-04', ARRAY['Action', 'Drama'], 'UA', 'Telugu', 158, 'Vakkantham Vamsi', ARRAY['Allu Arjun', 'Anu Emmanuel'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/fHQAy0hHANT8BIRrLAQCfmLwIN4.jpg', NULL);

-- Adding Alia Bhatt movies
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Raazi', 'movie', 'A young Kashmiri woman is married into a Pakistani military family to spy for India during the 1971 war. This gripping spy thriller showcases Alia Bhatt''s nuanced performance as she navigates the moral complexities of patriotism and betrayal while maintaining her cover in increasingly dangerous circumstances.', '2018-05-11', ARRAY['Thriller', 'Drama'], 'UA', 'Hindi', 138, 'Meghna Gulzar', ARRAY['Alia Bhatt', 'Vicky Kaushal'], ARRAY['Amazon Prime'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/fF2xXApETxZqyluokyJ1x4gIiTf.jpg', NULL),
('Highway', 'movie', 'A young woman kidnapped before her wedding develops Stockholm syndrome and finds unexpected freedom in her captivity. This road drama features one of Alia Bhatt''s most transformativeearly performances as she portrays a complex emotional journey through Indias diverse landscapes while forming a bond with her abductor.', '2014-02-21', ARRAY['Drama', 'Road Movie'], 'UA', 'Hindi', 133, 'Imtiaz Ali', ARRAY['Alia Bhatt', 'Randeep Hooda'], ARRAY['Disney+Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/xuTevYF35WDkElpm5vNBVaISkT9.jpg', NULL),
('Udta Punjab', 'movie', 'Four lives intersect amid Punjabs drug epidemic - a rockstar, a migrant worker, a doctor, and a cop. Alia Bhatt delivers a powerful performance as a Bihari laborer caught in the narcotics underworld in this gritty drama that exposed the devastating impact of drug abuse on Punjabi youth.', '2016-06-17', ARRAY['Drama', 'Crime'], 'A', 'Hindi', 148, 'Abhishek Chaubey', ARRAY['Alia Bhatt', 'Shahid Kapoor', 'Diljit Dosanjh'], ARRAY['Netflix'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/c7BXGhHwvK1AfDCmfPTtw5LsuIU.jpg', NULL),
('Dear Zindagi', 'movie', 'A cinematographer struggling with life and relationships finds new perspective through conversations with an unconventional therapist. This slice-of-life drama features Alia Bhatt in a relatable performance about mental health, self-discovery, and learning to embrace lifes imperfections.', '2016-11-25', ARRAY['Drama', 'Slice of Life'], 'U', 'Hindi', 151, 'Gauri Shinde', ARRAY['Alia Bhatt', 'Shah Rukh Khan'], ARRAY['Netflix'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/oUg0N2isgZ5rrxdXnsemcKolfKZ.jpg', NULL),
('Gangubai Kathiawadi', 'movie', 'The true story of a girl sold into prostitution who becomes the powerful madam of Kamathipura and a champion for sex workers rights. Alia Bhatt transforms into the titular character in this bold biopic that showcases her range as she portrays Gangubais journey from victim to queen.', '2022-02-25', ARRAY['Biography', 'Drama'], 'A', 'Hindi', 152, 'Sanjay Leela Bhansali', ARRAY['Alia Bhatt', 'Vijay Raaz'], ARRAY['Netflix'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/wHPEKlzg7CaJFCjWlMdZKpCRIDl.jpg', NULL);

-- Adding Deepika Padukone movies
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Chennai Express', 'movie', 'A mans journey to immerse his grandfathers ashes turns into a madcap adventure when he gets entangled with a dons daughter. Deepika Padukone shines as the feisty South Indian belle in this Rohit Shetty action-comedy that became one of Bollywoods highest-grossing films.', '2013-08-08', ARRAY['Action', 'Comedy'], 'U', 'Hindi', 141, 'Rohit Shetty', ARRAY['Deepika Padukone', 'Shah Rukh Khan'], ARRAY['Netflix'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/yPk3RUemG8TzuMDV3WOtPK5SgCH.jpg', NULL),
('Yeh Jawaani Hai Deewani', 'movie', 'An introverted doctor reunites with her free-spirited ex-crush during a friends wedding, rekindling old feelings. Deepika Padukone delivers a charming performance as Naina in this coming-of-age romantic drama about friendship, love, and choosing between dreams and relationships.', '2013-05-31', ARRAY['Romance', 'Drama'], 'U', 'Hindi', 160, 'Ayan Mukerji', ARRAY['Deepika Padukone', 'Ranbir Kapoor'], ARRAY['Netflix'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/em39H81XLCDgXsI7V4IcBZseEO6.jpg', NULL),
('Bajirao Mastani', 'movie', 'The epic historical romance between Maratha general Bajirao and his second wife Mastani. Deepika Padukone embodies the warrior princess Mastani in this visually stunning period drama that showcases her dancing, action, and emotional acting prowess.', '2015-12-18', ARRAY['Historical', 'Romance'], 'UA', 'Hindi', 158, 'Sanjay Leela Bhansali', ARRAY['Deepika Padukone', 'Ranveer Singh'], ARRAY['Amazon Prime'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/a3kM4CBTSI4NC8KYeSRJCh55liV.jpg', NULL),
('Padmaavat', 'movie', 'The legendary Rajput queen Padmavati chooses death over dishonor when the tyrannical Alauddin Khilji besieges her kingdom. Deepika Padukone commands the screen as the graceful yet fierce queen in this controversial historical epic known for its opulent visuals and grand scale.', '2018-01-25', ARRAY['Historical', 'Drama'], 'UA', 'Hindi', 164, 'Sanjay Leela Bhansali', ARRAY['Deepika Padukone', 'Ranveer Singh'], ARRAY['Amazon Prime'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/5kk71s8Vmvt8XQOojevhTA5QcB0.jpg', NULL),
('Chhapaak', 'movie', 'The true story of acid attack survivor Laxmi Agarwals fight for justice and rehabilitation. Deepika Padukone delivers a transformative performance in this hard-hitting drama that exposes the horrors of acid violence while celebrating the resilience of survivors.', '2020-01-10', ARRAY['Biography', 'Drama'], 'UA', 'Hindi', 120, 'Meghna Gulzar', ARRAY['Deepika Padukone', 'Vikrant Massey'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9Q1Iq9JQYqY', 'https://www.themoviedb.org/t/p/w1280/cr5KqiolMMRUEJxrNLWESxyVVeU.jpg', NULL);

-- Adding 5 English movies
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Inception', 'movie', 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into a CEOs mind. Christopher Nolans mind-bending sci-fi thriller explores the architecture of the subconscious with stunning visuals and a complex narrative structure that blurs the line between dreams and reality.', '2010-07-16', ARRAY['Sci-Fi', 'Action'], 'PG-13', 'English', 148, 'Christopher Nolan', ARRAY['Leonardo DiCaprio', 'Joseph Gordon-Levitt'], ARRAY['Amazon Prime'], 'https://youtu.be/YoHD9XEInc0', 'https://www.themoviedb.org/t/p/w1280/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg', NULL),
('The Shawshank Redemption', 'movie', 'Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency. This timeless drama about hope and friendship in the face of injustice features career-defining performances from Tim Robbins and Morgan Freeman.', '1994-09-23', ARRAY['Drama'], 'R', 'English', 142, 'Frank Darabont', ARRAY['Tim Robbins', 'Morgan Freeman'], ARRAY['Netflix'], 'https://youtu.be/6hB3S9bIaco', 'https://www.themoviedb.org/t/p/w1280/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', NULL),
('The Dark Knight', 'movie', 'When the menace known as the Joker emerges, Batman must confront chaos while questioning everything he stands for. Heath Ledgers iconic performance as the anarchic villain elevates this superhero film into a gripping crime epic about order versus chaos.', '2008-07-18', ARRAY['Action', 'Crime'], 'PG-13', 'English', 152, 'Christopher Nolan', ARRAY['Christian Bale', 'Heath Ledger'], ARRAY['HBO Max'], 'https://youtu.be/EXeTwQWrcwY', 'https://www.themoviedb.org/t/p/w1280/qJ2tW6WMUDux911r6m7haRef0WH.jpg', NULL),
('Forrest Gump', 'movie', 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75. Tom Hanks delivers an Oscar-winning performance in this heartwarming tale about life''s unpredictability and simple wisdom.', '1994-07-06', ARRAY['Drama', 'Romance'], 'PG-13', 'English', 142, 'Robert Zemeckis', ARRAY['Tom Hanks', 'Robin Wright'], ARRAY['Netflix'], 'https://youtu.be/bLvqoHBptjg', 'https://www.themoviedb.org/t/p/w1280/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', NULL),
('The Godfather', 'movie', 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son. Francis Ford Coppola''s masterpiece explores power, family, and the American dream through the Corleone crime family in this definitive gangster epic that redefined cinema.', '1972-03-24', ARRAY['Crime', 'Drama'], 'R', 'English', 175, 'Francis Ford Coppola', ARRAY['Marlon Brando', 'Al Pacino'], ARRAY['Amazon Prime'], 'https://youtu.be/sY1S34973zA', 'https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', NULL);

-- TV Shows
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Breaking Bad', 'show', 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family''s future. This character-driven saga follows Walter White''s shocking transformation from meek teacher to ruthless drug kingpin, exploring morality, consequence, and the fragility of the American dream.', '2008-01-20', ARRAY['Crime', 'Drama', 'Thriller'], 'TV-MA', 'English', 47, 'Vince Gilligan', ARRAY['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'], ARRAY['Netflix'], 'https://youtu.be/HhesaQXLuRY', 'https://www.themoviedb.org/t/p/w1280/ineLOBPG8AZsluYwnkMpHRyu7L.jpg', NULL),
('Stranger Things', 'show', 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl. This nostalgic homage to 1980s pop culture blends sci-fi, horror, and coming-of-age themes as a group of kids confront otherworldly threats and government conspiracies.', '2016-07-15', ARRAY['Drama', 'Fantasy', 'Horror'], 'TV-14', 'English', 50, 'The Duffer Brothers', ARRAY['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'], ARRAY['Netflix'], 'https://youtu.be/b9EkMc79ZSU', 'https://www.themoviedb.org/t/p/w1280/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg', NULL),
('The Office', 'show', 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium. This groundbreaking comedy finds humor in the mundane lives of Dunder Mifflin employees, led by the hilariously awkward regional manager Michael Scott.', '2005-03-24', ARRAY['Comedy'], 'TV-14', 'English', 22, 'Greg Daniels', ARRAY['Steve Carell', 'John Krasinski', 'Jenna Fischer'], ARRAY['Peacock'], 'https://youtu.be/tNcDHWpselE', 'https://www.themoviedb.org/t/p/w1280/dg9e5fPRRId8PoBE0F6jl5y85Eu.jpg', NULL),
('Friends', 'show', 'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan. This iconic sitcom about chosen family defined a generation with its relatable humor, memorable catchphrases, and the enduring bonds between Monica, Chandler, Ross, Rachel, Joey, and Phoebe.', '1994-09-22', ARRAY['Comedy', 'Romance'], 'TV-14', 'English', 22, 'David Crane', ARRAY['Jennifer Aniston', 'Courteney Cox', 'Lisa Kudrow'], ARRAY['Netflix'], 'https://youtu.be/hDNNmeeJs1Q', 'https://www.themoviedb.org/t/p/w1280/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg', NULL),
('Game of Thrones', 'show', 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia. This epic fantasy redefined television with its sprawling narrative, complex characters, and willingness to subvert expectations in its brutal depiction of power struggles.', '2011-04-17', ARRAY['Drama', 'Fantasy'], 'TV-MA', 'English', 57, 'David Benioff', ARRAY['Emilia Clarke', 'Kit Harington', 'Peter Dinklage'], ARRAY['HBO Max'], 'https://youtu.be/gcTkNV5Vg1E', 'https://www.themoviedb.org/t/p/w1280/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg', NULL),
('The Crown', 'show', 'This drama follows the political rivalries and romance of Queen Elizabeth II''s reign and the events that shaped the second half of the 20th century. Lavishly produced, the series offers an intimate look at the personal sacrifices and challenges behind the public facade of the British monarchy.', '2016-11-04', ARRAY['Biography', 'Drama'], 'TV-MA', 'English', 55, 'Peter Morgan', ARRAY['Claire Foy', 'Olivia Colman', 'Matt Smith'], ARRAY['Netflix'], 'https://youtu.be/JWtnJjn6ng0', 'https://www.themoviedb.org/t/p/w1280/1DDE0Z2Y805rqfkEjPbZsMLyPwa.jpg', NULL),
('Dark', 'show', 'A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations. This German sci-fi thriller weaves an intricate time-travel narrative that explores how the past, present, and future are interconnected in unsettling ways.', '2017-12-01', ARRAY['Drama', 'Mystery', 'Sci-Fi'], 'TV-MA', 'German', 53, 'Baran bo Odar', ARRAY['Louis Hofmann', 'Lisa Vicari', 'Oliver Masucci'], ARRAY['Netflix'], 'https://youtu.be/ESEUoa-mz2c', 'https://www.themoviedb.org/t/p/w1280/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg', NULL),
('Money Heist', 'show', 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain. Dressed in red jumpsuits and Salvador Dalí masks, the Professor''s crew executes an elaborate plan while authorities and hostages alike fall under their psychological sway.', '2017-05-02', ARRAY['Crime', 'Drama', 'Thriller'], 'TV-MA', 'Spanish', 45, 'Álex Pina', ARRAY['Úrsula Corberó', 'Álvaro Morte', 'Itziar Ituño'], ARRAY['Netflix'], 'https://youtu.be/fvCdLmxnkj0', 'https://www.themoviedb.org/t/p/w1280/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg', NULL),
('Peaky Blinders', 'show', 'A notorious gang in 1919 Birmingham, England, is led by the fierce Tommy Shelby, a crime boss set on moving up in the world no matter the cost. This stylish period drama follows the Shelby crime family''s rise to power amid post-WWI upheaval, featuring razor-blade caps and a killer soundtrack.', '2013-09-12', ARRAY['Crime', 'Drama'], 'TV-MA', 'English', 55, 'Steven Knight', ARRAY['Cillian Murphy', 'Paul Anderson', 'Helen McCrory'], ARRAY['Netflix'], 'https://youtu.be/oVzVdvGIC7U', 'https://www.themoviedb.org/t/p/w1280/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg', NULL),
('The Mandalorian', 'show', 'After the fall of the Galactic Empire, a lone gunfighter makes his way through the lawless outer reaches of the galaxy. This Star Wars spin-off introduced Baby Yoda (Grogu) and expanded the franchise''s mythology with Western-inspired storytelling and groundbreaking visual effects.', '2019-11-12', ARRAY['Action', 'Adventure', 'Sci-Fi'], 'TV-14', 'English', 40, 'Jon Favreau', ARRAY['Pedro Pascal', 'Gina Carano'], ARRAY['Disney+'], 'https://youtu.be/aOC8E8z_ifw', 'https://www.themoviedb.org/t/p/w1280/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg', NULL),
('The Witcher', 'show', 'Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts. Based on the fantasy novels, this series weaves together multiple timelines in its exploration of destiny, magic, and political intrigue in the Continent.', '2019-12-20', ARRAY['Action', 'Fantasy'], 'TV-MA', 'English', 60, 'Lauren Schmidt Hissrich', ARRAY['Henry Cavill', 'Anya Chalotra', 'Freya Allan'], ARRAY['Netflix'], 'https://youtu.be/ndl1W4ltcmg', 'https://www.themoviedb.org/t/p/w1280/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg', NULL),
('Better Call Saul', 'show', 'The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman. This Breaking Bad prequel explores Jimmy''s transformation into the sleazy Saul Goodman through morally ambiguous legal cases and his complex relationship with Kim Wexler.', '2015-02-08', ARRAY['Crime', 'Drama'], 'TV-MA', 'English', 46, 'Vince Gilligan', ARRAY['Bob Odenkirk', 'Rhea Seehorn'], ARRAY['Netflix'], 'https://youtu.be/HtqXL94Rza4', 'https://www.themoviedb.org/t/p/w1280/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg', NULL),
('Sherlock', 'show', 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London. Benedict Cumberbatch''s brilliant, high-functioning sociopath Sherlock Holmes uses deductive reasoning and technological savvy to solve baffling cases in this stylish reinvention of Arthur Conan Doyle''s detective.', '2010-07-25', ARRAY['Crime', 'Drama', 'Mystery'], 'TV-14', 'English', 88, 'Mark Gatiss', ARRAY['Benedict Cumberbatch', 'Martin Freeman', 'Andrew Scott'], ARRAY['Netflix'], 'https://youtu.be/xK7S9mrFWL4', 'https://www.themoviedb.org/t/p/w1280/cIfGAkpvWD2zxHrXzhv3uptYbyV.jpg', NULL),
('House of the Dragon', 'show', 'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. This Game of Thrones prequel depicts the beginning of the end of House Targaryen''s reign, setting the stage for the devastating civil war known as the Dance of the Dragons.', '2022-08-21', ARRAY['Drama', 'Fantasy'], 'TV-MA', 'English', 58, 'Miguel Sapochnik', ARRAY['Emma DArcy', 'Matt Smith', 'Olivia Cooke'], ARRAY['HBO Max'], 'https://youtu.be/DotnJ7tTA34', 'https://www.themoviedb.org/t/p/w1280/oxmdHR5Ka28HAJuMmS2hk5K6QQY.jpg', NULL),
('The Boys', 'show', 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers. This subversive take on the superhero genre explores celebrity, corporate power, and moral ambiguity as ordinary humans challenge god-like beings controlled by the sinister Vought Corporation.', '2019-07-26', ARRAY['Action', 'Comedy', 'Crime'], 'TV-MA', 'English', 60, 'Eric Kripke', ARRAY['Karl Urban', 'Jack Quaid', 'Antony Starr'], ARRAY['Amazon Prime'], 'https://youtu.be/06rueu_fh30', 'https://www.themoviedb.org/t/p/w1280/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg', NULL),
('How I Met Your Mother', 'show', 'Ted Mosby recounts to his children the events leading up to how he met their mother. This inventive sitcom plays with narrative structure and running gags as Ted and his friends navigate dating, careers, and growing up in New York City over nine seasons of romantic misadventures.', '2005-09-19', ARRAY['Comedy', 'Romance'], 'TV-14', 'English', 22, 'Carter Bays', ARRAY['Josh Radnor', 'Neil Patrick Harris', 'Cobie Smulders'], ARRAY['Hulu'], 'https://youtu.be/l_7oz3al8cs', 'https://www.themoviedb.org/t/p/w1280/b34jPzmB0wZy7EjUZoleXOl2RRI.jpg', NULL),
('The Big Bang Theory', 'show', 'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory. This long-running sitcom brought geek culture into the mainstream with its ensemble of lovable science nerds and their romantic entanglements.', '2007-09-24', ARRAY['Comedy', 'Romance'], 'TV-14', 'English', 22, 'Chuck Lorre', ARRAY['Jim Parsons', 'Johnny Galecki', 'Kaley Cuoco'], ARRAY['HBO Max'], 'https://youtu.be/W2xYwXGtY8U', 'https://www.themoviedb.org/t/p/w1280/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg', NULL),
('Squid Game', 'show', 'Hundreds of cash-strapped players accept a strange invitation to compete in children''s games for a tempting prize, but the stakes are deadly. This Korean survival drama became a global phenomenon with its brutal social commentary on inequality and desperate measures for financial freedom.', '2021-09-17', ARRAY['Drama', 'Thriller'], 'TV-MA', 'Korean', 55, 'Hwang Dong-hyuk', ARRAY['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon'], ARRAY['Netflix'], 'https://youtu.be/oqxAJKy0ii4', 'https://www.themoviedb.org/t/p/w1280/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg', NULL),
('Lost', 'show', 'The survivors of a plane crash find themselves stranded on a mysterious island with no way to escape. This genre-bending series blends survival drama with supernatural elements and complex character backstories, keeping viewers guessing with its mythology about the island''s secrets.', '2004-09-22', ARRAY['Drama', 'Mystery', 'Sci-Fi'], 'TV-14', 'English', 42, 'J.J. Abrams', ARRAY['Matthew Fox', 'Evangeline Lilly', 'Jorge Garcia'], ARRAY['Hulu'], 'https://youtu.be/7sLBzHWZ3YI', 'https://www.themoviedb.org/t/p/w1280/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg', NULL),
('Black Mirror', 'show', 'An anthology series exploring a twisted, high-tech multiverse where humanity''s greatest innovations and darkest instincts collide. Each standalone episode presents a dystopian vision of our technology-obsessed society, offering unsettling reflections on modern life through sci-fi parables.', '2011-12-04', ARRAY['Drama', 'Sci-Fi', 'Thriller'], 'TV-MA', 'English', 60, 'Charlie Brooker', ARRAY['Various'], ARRAY['Netflix'], 'https://youtu.be/jDiYGjp5iFg', 'https://www.themoviedb.org/t/p/w1280/5UaYsGZOFhjFDwQh6GuLjjA1WlF.jpg', NULL);

-- Anime
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Attack on Titan', 'anime', 'After his hometown is destroyed and his mother killed by giant humanoid creatures called Titans, Eren Yeager vows to eradicate them by joining the elite Survey Corps. This dark fantasy explores the brutality of war, the cycle of violence, and the shocking truths behind the Titans as humanity fights for survival within massive walled cities.', '2013-04-07', ARRAY['Action', 'Fantasy', 'Drama'], 'R', 'Japanese', 24, 'Tetsurō Araki', ARRAY['Yuki Kaji', 'Yui Ishikawa', 'Marina Inoue'], ARRAY['Crunchyroll', 'Netflix'], 'https://youtu.be/MGRm4IzK1SQ', 'https://www.themoviedb.org/t/p/w1280/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg', NULL),
('Death Note', 'anime', 'Light Yagami, a brilliant high school student, discovers a mysterious notebook that can kill anyone whose name is written in it. As he begins eliminating criminals under the alias "Kira," the eccentric detective L begins tracking him down in this psychological cat-and-mouse game about justice, power, and morality.', '2006-10-04', ARRAY['Mystery', 'Thriller', 'Supernatural'], 'R', 'Japanese', 23, 'Tetsurō Araki', ARRAY['Mamoru Miyano', 'Aya Hirano', 'Kappei Yamaguchi'], ARRAY['Netflix'], 'https://youtu.be/NlJZ-YgAt-c', 'https://www.themoviedb.org/t/p/w1280/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg', NULL),
('Demon Slayer: Kimetsu no Yaiba', 'anime', 'After his family is slaughtered and his sister Nezuko turned into a demon, Tanjiro Kamado becomes a demon slayer to find a cure for her and avenge his loved ones. This visually stunning series combines breathtaking swordplay with emotional storytelling as Tanjiro battles increasingly powerful demons while protecting his sister''s remaining humanity.', '2019-04-06', ARRAY['Action', 'Supernatural'], 'PG-13', 'Japanese', 24, 'Haruo Sotozaki', ARRAY['Natsuki Hanae', 'Akari Kitō', 'Hiro Shimono'], ARRAY['Crunchyroll', 'Netflix'], 'https://youtu.be/VQGCKyvzIM4', 'https://www.themoviedb.org/t/p/w1280/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg', NULL),
('One Punch Man', 'anime', 'Saitama, a hero who can defeat any opponent with a single punch, grows bored from lack of challenge in his fight against evil. This hilarious parody of superhero tropes follows Saitama''s search for a worthy opponent while dealing with the bureaucracy of hero rankings and the frustration that nobody recognizes his strength.', '2015-10-05', ARRAY['Action', 'Comedy', 'Sci-Fi'], 'PG-13', 'Japanese', 23, 'Shingo Natsume', ARRAY['Makoto Furukawa', 'Kaito Ishikawa', 'Hiroki Yasumoto'], ARRAY['Netflix', 'Hulu'], 'https://youtu.be/Poo5lqoWSGw', 'https://www.themoviedb.org/t/p/w1280/jbYJuxfZMpYDalkiOnBcCv9TaL.jpg', NULL),
('Naruto', 'anime', 'Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village''s leader and strongest ninja. This coming-of-age story explores themes of perseverance, friendship, and acceptance as Naruto overcomes prejudice and grows from a class clown to a hero.', '2002-10-03', ARRAY['Action', 'Adventure'], 'PG-13', 'Japanese', 23, 'Hayato Date', ARRAY['Junko Takeuchi', 'Chie Nakamura', 'Noriaki Sugiyama'], ARRAY['Crunchyroll', 'Netflix'], 'https://youtu.be/_dnkKfM3pyg', 'https://www.themoviedb.org/t/p/w1280/xppeysfvDKVx775MFuH8Z9BlpMk.jpg', NULL),
('Fullmetal Alchemist: Brotherhood', 'anime', 'After a failed alchemical experiment leaves them physically damaged, brothers Edward and Alphonse Elric search for the Philosopher''s Stone to restore their bodies. This complete adaptation of the manga explores the cost of human ambition, the bonds of brotherhood, and the consequences of playing god through alchemy.', '2009-04-05', ARRAY['Action', 'Adventure', 'Fantasy'], 'PG-13', 'Japanese', 24, 'Yasuhiro Irie', ARRAY['Romi Park', 'Rie Kugimiya', 'Shinichiro Miki'], ARRAY['Crunchyroll', 'Netflix'], 'https://youtu.be/d4M0KNJDPiQ', 'https://www.themoviedb.org/t/p/w1280/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg', NULL),
('Tokyo Ghoul', 'anime', 'College student Ken Kaneki becomes a half-ghoul after an encounter with one, forcing him to survive in both human and ghoul societies while resisting his growing bloodlust. This dark fantasy examines identity, discrimination, and what it means to be human as Kaneki struggles with his monstrous nature and the violent politics of ghoul factions.', '2014-07-04', ARRAY['Horror', 'Supernatural', 'Action'], 'R', 'Japanese', 24, 'Shuhei Morita', ARRAY['Natsuki Hanae', 'Sora Amamiya'], ARRAY['Funimation', 'Netflix'], 'https://youtu.be/7aMOurgDB-o', 'https://www.themoviedb.org/t/p/w1280/1m4RlC9BTCbyY549TOdVQ5NRPcR.jpg', NULL),
('Jujutsu Kaisen', 'anime', 'When high schooler Yuji Itadori swallows a cursed object containing a powerful spirit, he becomes host to the curse and enrolls in Tokyo''s Jujutsu Technical High School to control it. This supernatural action series blends horror elements with dynamic fight choreography as Yuji trains to become a jujutsu sorcerer battling curses.', '2020-10-03', ARRAY['Action', 'Fantasy'], 'PG-13', 'Japanese', 24, 'Sunghoo Park', ARRAY['Junya Enoki', 'Yuma Uchida', 'Yuichi Nakamura'], ARRAY['Crunchyroll'], 'https://youtu.be/f7R2U1JxL6U', 'https://www.themoviedb.org/t/p/w1280/fHpKWq9ayzSk8nSwqRuaAUemRKh.jpg', NULL),
('My Hero Academia', 'anime', 'In a world where most people have superpowers called Quirks, powerless Izuku Midoriya inherits the abilities of the greatest hero, All Might. As he attends UA High School for aspiring heroes, Deku must prove himself worthy of One For All while facing villains, rival students, and the tremendous responsibility that comes with his power.', '2016-04-03', ARRAY['Action', 'Comedy', 'Superhero'], 'PG-13', 'Japanese', 24, 'Kenji Nagasaki', ARRAY['Daiki Yamashita', 'Nobuhiko Okamoto', 'Kenta Miyake'], ARRAY['Crunchyroll', 'Netflix'], 'https://youtu.be/wIb3nnOeves', 'https://www.themoviedb.org/t/p/w1280/phuYuzqWW9ru8EA3HVjE9W2Rr3M.jpg', NULL);

-- Korean Dramas (Additional 15)
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('It''s Okay to Not Be Okay', 'show', 'A poignant tale of emotional healing between an antisocial children''s book author with antisocial personality disorder and a selfless psychiatric caretaker who lives with his autistic older brother. Set against the backdrop of a psychiatric hospital, this visually stunning drama explores trauma, mental health, and unconventional love through fairy tale metaphors and gothic aesthetics.', '2020-06-20', ARRAY['Romance', 'Psychological'], 'TV-16', 'Korean', 70, 'Park Shin-woo', ARRAY['Kim Soo-hyun', 'Seo Ye-ji', 'Oh Jung-se'], ARRAY['Netflix'], 'https://youtu.be/1H__LNPCqDY', 'https://www.themoviedb.org/t/p/w1280/5pKlA16OaTLm57alV4EWuxIfO2O.jpg', NULL),
('Mr. Sunshine', 'show', 'Set in early 1900s Korea during the Joseon Dynasty, this epic historical drama follows a Korean-born U.S. Marine officer who returns to his homeland during political upheaval and falls for an aristocrat''s daughter. With cinematic production values, the series depicts Korea''s resistance against colonization while weaving a tragic romance across class divides and national loyalties.', '2018-07-07', ARRAY['Historical', 'Romance'], 'TV-16', 'Korean', 80, 'Lee Eung-bok', ARRAY['Lee Byung-hun', 'Kim Tae-ri', 'Yoo Yeon-seok'], ARRAY['Netflix'], 'https://youtu.be/8Cr7GfDfEWg', 'https://www.themoviedb.org/t/p/w1280/iftMALeIzTYYOVmPOCsS1mQvoNz.jpg', NULL),
('Sky Castle', 'show', 'A satirical drama exposing the cutthroat world of elite education as wealthy families in an exclusive residential area scheme to get their children into top universities at any cost. The series became a cultural phenomenon in Korea for its scathing critique of educational pressure, featuring manipulative tutors, ruthless parents, and shocking twists that reveal the dark side of academic obsession.', '2018-11-23', ARRAY['Drama', 'Satire'], 'TV-15', 'Korean', 65, 'Jo Hyun-tak', ARRAY['Yum Jung-ah', 'Lee Tae-ran', 'Yoon Se-ah'], ARRAY['Netflix'], 'https://youtu.be/3tqmTapTq7M', 'https://www.themoviedb.org/t/p/w1280/tE2b4DKYteipIBE51re62jLi6RU.jpg', NULL),
('Signal', 'show', 'A gripping crime thriller connecting past and present through a mysterious walkie-talkie that allows a modern-day detective to communicate with a cold case profiler from 1989. Based on real unsolved Korean crimes, the series masterfully blends police procedural elements with supernatural twists as the two officers work across time to solve decades-old murders while confronting police corruption.', '2016-01-22', ARRAY['Crime', 'Fantasy'], 'TV-16', 'Korean', 70, 'Kim Won-seok', ARRAY['Lee Je-hoon', 'Kim Hye-soo', 'Cho Jin-woong'], ARRAY['Netflix'], 'https://youtu.be/MfYwHXxKXg4', 'https://www.themoviedb.org/t/p/w1280/4MzvA9GpzztBTFWw5nHENj7hU9a.jpg', NULL),
('Hotel Del Luna', 'show', 'A supernatural fantasy revolving around a mystical hotel that caters exclusively to ghosts, run by the beautiful but ill-tempered CEO Jang Man-wol who has been bound to the establishment for 1,300 years as punishment for her sins. When a human manager gets entangled in her world, their fates intertwine in this visually spectacular drama blending horror, romance, and poignant ghost stories.', '2019-07-13', ARRAY['Fantasy', 'Horror'], 'TV-15', 'Korean', 75, 'Oh Choong-hwan', ARRAY['IU', 'Yeo Jin-goo'], ARRAY['Netflix'], 'https://youtu.be/60En6MY8Abg', 'https://www.themoviedb.org/t/p/w1280/8bizZsXoAsOTbhyFKfBogC8mgG2.jpg', NULL),
('Vagabond', 'show', 'A high-octane action thriller following a stuntman who uncovers a massive corruption conspiracy after his nephew dies in a mysterious plane crash. Teaming up with a NIS agent, they embark on a globetrotting investigation from Seoul to Morocco, facing political intrigue, corporate malfeasance, and deadly assassins in this cinematic series packed with breathtaking stunts and plot twists.', '2019-09-20', ARRAY['Action', 'Thriller'], 'TV-16', 'Korean', 70, 'Yoo In-sik', ARRAY['Lee Seung-gi', 'Bae Suzy'], ARRAY['Netflix'], 'https://youtu.be/9WXJ1ZI__-4', 'https://www.themoviedb.org/t/p/w1280/8Sud9wqG7WZMXesZhPZ4lergRvp.jpg', NULL),
('The King: Eternal Monarch', 'show', 'A parallel universe fantasy where a modern-day Korean emperor discovers a portal to alternate reality Korea where he meets a detective who may hold the key to defeating the interdimensional villain who murdered his father. This lavish production from the writer of Goblin blends quantum physics with royal intrigue and star-crossed romance across multiple dimensions.', '2020-04-17', ARRAY['Fantasy', 'Romance'], 'TV-14', 'Korean', 70, 'Baek Sang-hoon', ARRAY['Lee Min-ho', 'Kim Go-eun'], ARRAY['Netflix'], 'https://youtu.be/pvcOO0pXZR8', 'https://www.themoviedb.org/t/p/w1280/7SLlbkzOJb8v9wXVYIcqozx2hxe.jpg', NULL),
('While You Were Sleeping', 'show', 'A young woman who can see future tragedies in her dreams teams up with a prosecutor and a police officer to prevent the events from occurring. This clever legal fantasy blends supernatural elements with courtroom drama and romantic tension as the trio''s fates become increasingly intertwined through their shared visions and growing feelings.', '2017-09-27', ARRAY['Fantasy', 'Legal'], 'TV-14', 'Korean', 65, 'Oh Choong-hwan', ARRAY['Lee Jong-suk', 'Bae Suzy'], ARRAY['Netflix'], 'https://youtu.be/S14vX4bQN6I', 'https://www.themoviedb.org/t/p/w1280/g809WCxgOKWXip47Epmwh1ttmVP.jpg', NULL),
('Healer', 'show', 'A legendary night courier known only as "Healer" gets entangled with an idealistic journalist and a star reporter with a traumatic past. This action-packed romance follows their dangerous investigation into a decades-old conspiracy while the mysterious mercenary struggles with his growing feelings and moral dilemmas about his shadowy profession.', '2014-12-08', ARRAY['Action', 'Romance'], 'TV-14', 'Korean', 60, 'Lee Jung-sub', ARRAY['Ji Chang-wook', 'Park Min-young'], ARRAY['Netflix'], 'https://youtu.be/V1D8V_JYq4E', 'https://www.themoviedb.org/t/p/w1280/too4Zig9bDJOfvnFfU1SaxKmGlR.jpg', NULL),
('Weightlifting Fairy Kim Bok-joo', 'show', 'A coming-of-age sports romance following the life of a weightlifting athlete and her childhood friend who becomes a competitive swimmer. Set in a sports university, this heartwarming drama captures the struggles of young athletes with humor and sincerity as they navigate first love, family expectations, and the pressures of elite competition.', '2016-11-16', ARRAY['Romance', 'Sports'], 'TV-14', 'Korean', 60, 'Oh Hyun-jong', ARRAY['Lee Sung-kyoung', 'Nam Joo-hyuk'], ARRAY['Netflix'], 'https://youtu.be/uYp_4F2YJIg', 'https://www.themoviedb.org/t/p/w1280/oARcy8kubYekRqii04obOlvw442.jpg', NULL),
('Legend of the Blue Sea', 'show', 'A romantic fantasy about the last mermaid on Earth who travels to modern-day Seoul and falls for a cunning con artist with whom she shares a mystical connection from their past lives in Joseon-era Korea. This visually stunning drama blends comedy, fantasy, and melodrama while exploring themes of reincarnation and destined love.', '2016-11-16', ARRAY['Fantasy', 'Romance'], 'TV-14', 'Korean', 60, 'Jin Hyuk', ARRAY['Lee Min-ho', 'Jun Ji-hyun'], ARRAY['Netflix'], 'https://youtu.be/5RQX7BPlYq0', 'https://www.themoviedb.org/t/p/w1280/vhBdwKSYOvops4o68X1zNXqEDF1.jpg', NULL),
('W: Two Worlds', 'show', 'A groundbreaking fantasy thriller where a surgeon gets pulled into the webtoon world created by her father, where she meets the protagonist - a wealthy businessman with a tragic past. As the boundaries between reality and fiction blur, they must fight to control their destinies against the webtoon''s mysterious forces trying to kill the hero.', '2016-07-20', ARRAY['Fantasy', 'Thriller'], 'TV-14', 'Korean', 60, 'Jung Dae-yoon', ARRAY['Lee Jong-suk', 'Han Hyo-joo'], ARRAY['Netflix'], 'https://youtu.be/5VDAxE0u7CY', 'https://www.themoviedb.org/t/p/w1280/9WJMvid29p0XOzVhnsL1aJyoV4x.jpg', NULL),
('Strong Woman Do Bong-soon', 'show', 'A petite woman with superhuman strength becomes the bodyguard of a quirky gaming company CEO while secretly harboring feelings for her childhood friend turned police detective. This delightful romantic comedy combines slapstick humor with crime elements as the female lead struggles to control her powers and navigate her complicated love triangle.', '2017-02-24', ARRAY['Romance', 'Comedy'], 'TV-14', 'Korean', 60, 'Lee Hyung-min', ARRAY['Park Bo-young', 'Park Hyung-sik'], ARRAY['Netflix'], 'https://youtu.be/6LfRZ00gy6JXzPBKXVOqQuZJqKh', 'https://www.themoviedb.org/t/p/w1280/sPdS6oUdXfBNGKROE5RY5s5laqx.jpg', NULL),
('What''s Wrong With Secretary Kim', 'show', 'A narcissistic vice chairman of a major corporation faces existential crisis when his perfect secretary of nine years announces her resignation. As he tries everything to make her stay, buried childhood traumas and unexpected romantic feelings surface in this office romance that balances comedy with psychological depth.', '2018-06-06', ARRAY['Romance', 'Comedy'], 'TV-14', 'Korean', 60, 'Park Joon-hwa', ARRAY['Park Seo-joon', 'Park Min-young'], ARRAY['Netflix'], 'https://youtu.be/2Cg6T2yQoYk', 'https://www.themoviedb.org/t/p/w1280/w6muIYgrx1XZFombs3N8owfgLwf.jpg', NULL),
('Her Private Life', 'show', 'A professional art curator leads a double life as a passionate fangirl of a K-pop idol, until her secret hobby gets entangled with her fake relationship turned real with her intimidating new boss. This sweet rom-com explores fan culture and workplace romance with humor and insight into modern dating.', '2019-04-10', ARRAY['Romance', 'Comedy'], 'TV-14', 'Korean', 60, 'Hong Jong-chan', ARRAY['Park Min-young', 'Kim Jae-wook'], ARRAY['Netflix'], 'https://youtu.be/6LfRZ00gy6JXzPBKXVOqQuZJqKh', 'https://www.themoviedb.org/t/p/w1280/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg', NULL),
('Something in the Rain', 'show', 'A delicate romance blossoms between a single career woman in her 30s and her best friend''s younger brother who has returned after working abroad. Facing societal disapproval and workplace harassment, their relationship is tested in this realistic portrayal of modern love in conservative Korean society.', '2018-03-30', ARRAY['Romance', 'Drama'], 'TV-16', 'Korean', 70, 'Ahn Pan-seok', ARRAY['Son Ye-jin', 'Jung Hae-in'], ARRAY['Netflix'], 'https://youtu.be/6LfRZ00gy6JXzPBKXVOqQuZJqKh', 'https://www.themoviedb.org/t/p/w1280/sTNXMCASbNn7cSzcQ7DVazixnAc.jpg', NULL);

-- Chinese Dramas (Additional 15)
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('The Untamed', 'show', 'Based on the BL novel Mo Dao Zu Shi, this xianxia drama follows the tumultuous relationship between two cultivation sect disciples - the rebellious Wei Wuxian and righteous Lan Wangji - as they uncover a dark conspiracy spanning past and present lives. Despite censorship limitations, the series became a global phenomenon for its profound emotional depth, intricate world-building, and subtle portrayal of a soulmate bond that transcends death.', '2019-06-27', ARRAY['Fantasy', 'Wuxia'], 'TV-14', 'Mandarin', 45, 'Chan Ka Lam', ARRAY['Xiao Zhan', 'Wang Yibo'], ARRAY['Netflix', 'WeTV'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/8TZbpPpLQVS2i7P7yUVhrFlFsmW.jpg', NULL),
('Eternal Love (Ten Miles of Peach Blossoms)', 'show', 'An epic three-life romance between the High Goddess Bai Qian and Heavenly Crown Prince Ye Hua, spanning 70,000 years across mortal and immortal realms. This masterpiece of xianxia genre features breathtaking fantasy landscapes, heart-wrenching sacrifices, and a love that persists through war, betrayal, and multiple reincarnations, setting new standards for Chinese period fantasy production.', '2017-01-30', ARRAY['Fantasy', 'Romance'], 'TV-14', 'Mandarin', 45, 'Lin Yufen', ARRAY['Yang Mi', 'Mark Chao'], ARRAY['Netflix', 'Viki'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/c7Pfx7dQiRsi1rU8N9s05gHnAkI.jpg', NULL),
('Love Between Fairy and Devil', 'show', 'When a low-ranking fairy accidentally breaks the seal on the terrifying Demon Lord Dongfang Qingcang, she becomes entangled in his quest to regain his powers while he slowly develops human emotions through their forced connection. This 2022 phenomenon blends stunning CGI with a enemies-to-lovers romance, featuring one of the most compelling antihero arcs in xianxia history.', '2022-08-07', ARRAY['Fantasy', 'Romance'], 'TV-14', 'Mandarin', 45, 'Ivy Lin', ARRAY['Esther Yu', 'Dylan Wang'], ARRAY['Netflix', 'iQIYI'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/mNgUuTGkOj19Z09zKa76bE6J5Di.jpg', NULL),
('Nirvana in Fire', 'show', 'Widely considered one of the greatest Chinese dramas ever made, this political intrigue masterpiece follows Mei Changsu, a frail scholar who returns to the capital under a new identity to clear his family''s name after being framed for treason 12 years prior. With brilliant strategizing worthy of Chinese "Three Kingdoms" tales, he manipulates court factions while hiding his terminal illness and true identity as the former young marshal of the Chiyan Army.', '2015-09-19', ARRAY['Historical', 'Political'], 'TV-14', 'Mandarin', 45, 'Li Xue', ARRAY['Hu Ge', 'Liu Tao'], ARRAY['Viki'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/taqGVujrSxaRrEXuGlIHGVRi3m4.jpg', NULL),
('The Long Ballad', 'show', 'Based on the manhua "Chang Ge Xing", this historical drama follows Princess Li Changge who escapes after her family is massacred in a coup, disguising herself as a man to seek revenge while becoming entangled with the formidable Ashile Sun of the nomadic tribes. Set during Tang Dynasty political upheavals, the series delivers breathtaking battle sequences, nuanced character development, and a mature romance between two equally strong-willed warriors.', '2021-03-31', ARRAY['Historical', 'Romance'], 'TV-14', 'Mandarin', 45, 'Zhu Ruibin', ARRAY['Dilraba Dilmurat', 'Wu Lei'], ARRAY['WeTV'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/tens9Bq3bWsrObwxUDKPwecNmgr.jpg', NULL),
('Go Ahead', 'show', 'A heartwarming family drama about three traumatized children - Li Jianjian, Ling Xiao and He Ziqiu - who form an unconventional family under one roof despite having no blood relation. The story alternates between their childhood healing from abandonment issues and their adult lives as they navigate romantic feelings, career challenges, and the return of biological family members threatening their bond.', '2020-08-10', ARRAY['Family', 'Drama'], 'TV-14', 'Mandarin', 45, 'Ding Ziguang', ARRAY['Tan Songyun', 'Song Weilong'], ARRAY['iQIYI'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/75SigmLMhs3x4rA149w2hxT3iXD.jpg', NULL),
('Joy of Life', 'show', 'A modern man reincarnates into the body of Fan Xian, the illegitimate son of a high-ranking official in a fictional historical dynasty. Using his 21st century knowledge and wit, he navigates court intrigues while uncovering secrets about his mysterious birth and the death of his mother, a legendary businesswoman who may have also been a time traveler. The series uniquely blends political drama with metafictional humor and sci-fi elements.', '2019-11-26', ARRAY['Historical', 'Comedy'], 'TV-14', 'Mandarin', 45, 'Sun Hao', ARRAY['Zhang Ruoyun', 'Li Qin'], ARRAY['WeTV'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/vlHJfLsduZiILN8eYdN57kHZTcQ.jpg', NULL),
('Word of Honor', 'show', 'This wuxia BL adaptation follows the unlikely bond between Zhou Zishu, former leader of an assassin organization seeking redemption, and Wen Kexing, the mysterious and flirtatious master of Ghost Valley. Their journey to uncover martial arts world conspiracies develops into a profound soulmate connection, celebrated for its chemistry-filled performances and faithful adaptation of the danmei novel "Faraway Wanderers".', '2021-02-22', ARRAY['Wuxia', 'Action'], 'TV-14', 'Mandarin', 45, 'Li Hongyu', ARRAY['Zhang Zhehan', 'Gong Jun'], ARRAY['Youku'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/tV25b0Pl5R9rsl6iBIJej7qzK5a.jpg', NULL),
('The Bad Kids', 'show', 'A critically acclaimed crime thriller where three children accidentally film a murder while attempting to blackmail their math teacher, setting off a chain reaction of lies, cover-ups, and psychological manipulation. Told through unreliable perspectives, the series offers a dark commentary on childhood innocence, parental failure, and moral ambiguity in a small coastal town.', '2020-06-16', ARRAY['Crime', 'Thriller'], 'TV-MA', 'Mandarin', 45, 'Xin Shuang', ARRAY['Rong Zishan', 'Shi Pengyuan'], ARRAY['iQIYI'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/i8XHjbwBUbybCQoUJbT89JpcS1c.jpg', NULL),
('Reset', 'show', 'A groundbreaking time-loop thriller where passengers on a doomed bus repeatedly relive their final moments before an explosion. Student Li Shiqing and game designer Xiao Heyun must work together across repeated cycles to identify the bomber among them while uncovering the tragic backstory connecting all passengers. The tight 15-episode format creates relentless tension with each reset revealing new clues.', '2022-01-11', ARRAY['Sci-Fi', 'Thriller'], 'TV-14', 'Mandarin', 45, 'Sun Molong', ARRAY['Bai Jingting', 'Zhao Jinmai'], ARRAY['Tencent Video'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/t95T31wxF0ElSwUE4U8AnOSAmF3.jpg', NULL),
('Love O2O', 'show', 'A quintessential campus romance between computer science genius Xiao Nai and beauty Bei Weiwei, who bond over online gaming before meeting in real life at university. The series set new standards for gaming-related CGI and portrays an unusually healthy relationship between equally talented leads navigating career ambitions and school life without typical breakup tropes.', '2016-08-22', ARRAY['Romance', 'Drama'], 'TV-14', 'Mandarin', 45, 'Lin Yufen', ARRAY['Yang Yang', 'Zheng Shuang'], ARRAY['Netflix'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/zqXrBP6CRAX5FkAszdTWWHOb2bY.jpg', NULL),
('Story of Yanxi Palace', 'show', 'The most-watched Chinese drama of 2018 follows cunning maid Wei Yingluo''s rise through the ranks of the Qing Dynasty imperial harem to avenge her sister''s death. Praised for its strong female lead, intricate costume designs, and realistic portrayal of palace intrigue, the series offers a feminist reinterpretation of historical harem politics through Wei Yingluo''s strategic genius and refusal to play by traditional rules.', '2018-07-19', ARRAY['Historical', 'Drama'], 'TV-14', 'Mandarin', 45, 'Hui Kaidong', ARRAY['Wu Jinyan', 'Nie Yuan'], ARRAY['iQIYI'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/k6eVxXSsyK6ukKzdgn9eNCAiLJ0.jpg', NULL),
('Ashes of Love', 'show', 'A xianxia epic following the Flower Goddess'' daughter Jinmi who is born without the ability to love due to a potion administered by her mother. When she ventures beyond her isolated home, two princes - the Fire Immortal Xu Feng and Night Immortal Run Yu - become entangled in her awakening emotions, leading to celestial conflicts and heartbreaking sacrifices across heavenly and demon realms.', '2018-08-02', ARRAY['Fantasy', 'Romance'], 'TV-14', 'Mandarin', 45, 'Chu Ruihui', ARRAY['Yang Zi', 'Deng Lun'], ARRAY['Netflix'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/FdUxxXN0NqS03gxzKgxiWCobue.jpg', NULL),
('The Romance of Tiger and Rose', 'show', 'A hilarious meta-romance where screenwriter Chen Xiaoqian transmigrates into her own historical drama as the villainous princess who dies early in the story. Determined to survive, she tries to rewrite her fate by matchmaking the male lead with his destined partner while unexpectedly falling for the fictional Han Shuo, who begins developing self-awareness beyond his written character.', '2020-05-18', ARRAY['Romance', 'Comedy'], 'TV-14', 'Mandarin', 45, 'Cha Chuanyi', ARRAY['Zhao Lusi', 'Ding Yuxi'], ARRAY['Tencent Video'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/mCsidkxf6ji8e71T07dYff3FjCF.jpg', NULL),
('Put Your Head on My Shoulder', 'show', 'A sweet university romance between physics major Gu Weiyi and accounting student Situ Mo who become unlikely roommates. The series captures the tender awkwardness of first love as the introverted genius and ordinary girl navigate living together, career uncertainties, and growing feelings through mundane yet heartwarming daily interactions.', '2019-04-10', ARRAY['Romance', 'Youth'], 'TV-14', 'Mandarin', 45, 'Zhu Dongning', ARRAY['Lin Yi', 'Xing Fei'], ARRAY['WeTV'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/zVYvodC12ZHGVPHX8LJjZHDERmK.jpg', NULL),
('Le Coup de Foudre', 'show', 'Based on the author''s real-life romance, this nostalgic drama follows Qiao Yi and Yan Mo from high school sweethearts to married couple, with flashbacks contrasting their youthful idealism with adult realities. The series stands out for its authentic portrayal of long-term relationships, showing both the romantic moments and difficult compromises that come with growing together over a decade.', '2019-04-10', ARRAY['Romance', 'Drama'], 'TV-14', 'Mandarin', 45, 'Wang Zhi', ARRAY['Janice Wu', 'Zhang Yu Jian'], ARRAY['Youku'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/jen6kiVpTSiJjqvsIrGc7MPtln7.jpg', NULL);

-- Indian Shows (Additional 15)
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Sacred Games', 'show', 'India''s first Netflix Original series follows troubled Mumbai police officer Sartaj Singh as he receives a cryptic warning from gangster Ganesh Gaitonde about the city''s impending doom. The dual narrative alternates between Sartaj''s present-day investigation and Gaitonde''s rise to power in the 1980s underworld, exposing shocking connections between crime, politics, and religion that threaten to destroy Mumbai.', '2018-07-06', ARRAY['Crime', 'Thriller'], 'TV-MA', 'Hindi', 50, 'Vikramaditya Motwane', ARRAY['Saif Ali Khan', 'Nawazuddin Siddiqui'], ARRAY['Netflix'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/uEbNtFbK4At9WBDGap23lt1qO9n.jpg', NULL),
('Mirzapur', 'show', 'A brutal crime saga set in the lawless badlands of Uttar Pradesh, where the iron-fisted Akhandanand Tripathi aka Kaleen Bhaiya rules the opium and gun trade through fear and violence. When two brothers get drawn into his empire, their thirst for revenge ignites a bloody gang war that consumes families, corrupts institutions, and redefines power in the criminal underworld.', '2018-11-16', ARRAY['Crime', 'Action'], 'TV-MA', 'Hindi', 50, 'Karan Anshuman', ARRAY['Pankaj Tripathi', 'Ali Fazal'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/p0qM8hhlMF5DuxHBzl2EZR6TehX.jpg', NULL),
('The Family Man', 'show', 'Srikant Tiwari is a middle-class man secretly working as an intelligence officer for TASC, a fictional branch of India''s National Investigation Agency. The series masterfully balances his high-stakes counterterrorism operations with domestic struggles, particularly when a mission involving Sri Lankan Tamil militants intersects with his family''s safety in this gripping spy thriller.', '2019-09-20', ARRAY['Action', 'Drama'], 'TV-14', 'Hindi', 45, 'Raj Nidimoru', ARRAY['Manoj Bajpayee', 'Priyamani'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/5l5uL40hrP3oKzD6zfh2F9b6XMd.jpg', NULL),
('Paatal Lok', 'show', 'When washed-up Delhi cop Hathiram Chaudhary is assigned an attempted assassination case, he uncovers connections between the would-be killers and a powerful journalist that lead down a rabbit hole of caste violence, political corruption, and media manipulation. This neo-noir crime drama presents a scathing portrait of modern India through its four-tiered cosmology of Swarg Lok (heaven), Dharti Lok (earth), and Paatal Lok (underworld).', '2020-05-15', ARRAY['Crime', 'Thriller'], 'TV-MA', 'Hindi', 45, 'Prosit Roy', ARRAY['Jaideep Ahlawat', 'Neeraj Kabi'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/duaaazbB49iKK4TMvekR3fQIVhU.jpg', NULL),
('Scam 1992: The Harshad Mehta Story', 'show', 'This critically acclaimed financial thriller chronicles the rise and fall of stockbroker Harshad Mehta who orchestrated India''s biggest securities scam in 1992, manipulating the Bombay Stock Exchange to the tune of ₹5,000 crore. The series offers a fascinating look at financial markets, media complicity, and regulatory failures through Mehta''s charismatic yet destructive ambition.', '2020-10-09', ARRAY['Biography', 'Crime'], 'TV-14', 'Hindi', 50, 'Hansal Mehta', ARRAY['Pratik Gandhi', 'Shreya Dhanwanthary'], ARRAY['Sony LIV'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/fiimZ9Xt5cPTPHNrbS4QautBXpU.jpg', NULL),
('Delhi Crime', 'show', 'Based on the infamous 2012 Nirbhaya gang rape case, this harrowing drama follows DCP Vartika Chaturvedi and her team as they race against time and systemic indifference to identify and apprehend the six perpetrators. The series unflinchingly examines institutional failures, societal attitudes toward women, and the emotional toll on investigators handling such brutal crimes.', '2019-03-22', ARRAY['Crime', 'Drama'], 'TV-MA', 'Hindi', 45, 'Richie Mehta', ARRAY['Shefali Shah', 'Rasika Dugal'], ARRAY['Netflix'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/xkpkTj6KGsjSaet0VQaq0aTn31D.jpg', NULL),
('Mismatched', 'show', 'A contemporary coming-of-age story following tech whiz Rishi and aspiring game designer Dimple as they navigate love and ambition at a summer coding program in Jaipur. The series refreshingly portrays modern Indian youth culture, tackling issues like online dating, career pressures, and interfaith relationships while maintaining the charm of classic romantic comedies.', '2020-11-20', ARRAY['Romance', 'Drama'], 'TV-14', 'Hindi', 40, 'Akarsh Khurana', ARRAY['Prajakta Koli', 'Rohit Saraf'], ARRAY['Netflix'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/l65kfL6qhTWd858OqGTr3RWwAUj.jpg', NULL),
('Kota Factory', 'show', 'Set in India''s notorious coaching hub Kota, this black-and-white dramedy follows Vaibhav and his friends as they endure the grueling preparation for IIT entrance exams. The series authentically captures student life in hostels, the pressures of academic expectations, and the small moments of rebellion that keep hope alive in this pressure-cooker environment.', '2019-04-16', ARRAY['Drama', 'Comedy'], 'TV-14', 'Hindi', 30, 'Raghav Subbu', ARRAY['Mayur More', 'Jitendra Kumar'], ARRAY['TVF Play'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/7Pi6b2gFgwKtxniTqFQNxHPsJQ.jpg', NULL);

-- Kannada Movies (5 Famous Films)
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('KGF: Chapter 1', 'movie', 'Set in the 1970s, this epic action drama follows Rocky, an ambitious young man who rises from poverty to become the king of the Kolar Gold Fields through sheer determination and brutal violence. The film redefined Kannada cinema''s scale with its grandiose visuals, powerful background score, and Yash''s iconic performance as the ruthless yet charismatic protagonist.', '2018-12-21', ARRAY['Action', 'Drama'], 'UA', 'Kannada', 155, 'Prashanth Neel', ARRAY['Yash', 'Srinidhi Shetty'], ARRAY['Amazon Prime'], 'https://youtu.be/qXgF-iJ_ezE', 'https://www.themoviedb.org/t/p/w1280/ltHlJwvxKv7d0ooCiKSAvfwV9tX.jpg', NULL),
('Kantara', 'movie', 'A mystical thriller rooted in Karnataka''s Bhoota Kola tradition, where a local demigod''s conflict with a forest officer escalates into a supernatural confrontation. Rishab Shetty''s directorial masterpiece blends indigenous folklore with stunning cinematography and an unforgettable climax that explores the complex relationship between humans, nature, and divine forces.', '2022-09-30', ARRAY['Action', 'Thriller'], 'UA', 'Kannada', 148, 'Rishab Shetty', ARRAY['Rishab Shetty', 'Sapthami Gowda'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/jIsKmkxMzdCZ0Ux1GVSnu8m6Na6.jpg', NULL),
('Garuda Gamana Vrishabha Vahana', 'movie', 'A gripping crime saga following the rise and fall of two childhood friends turned criminal overlords in Mangaluru. The film''s Shakespearean portrayal of brotherhood, betrayal, and bloody revenge is elevated by Raj B. Shetty''s raw direction and the leads'' electrifying performances, set against the backdrop of coastal Karnataka''s underworld.', '2021-11-19', ARRAY['Crime', 'Drama'], 'A', 'Kannada', 158, 'Raj B. Shetty', ARRAY['Raj B. Shetty', 'Rishab Shetty'], ARRAY['ZEE5'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/5jWfzHXvqLllbsVL7bvV1UVTq8s.jpg', NULL),
('Ulidavaru Kandanthe', 'movie', 'An anthology film presenting interconnected stories from coastal Karnataka, told through different narrative styles and timelines. Rakshit Shetty''s directorial debut revolutionized Kannada cinema with its nonlinear storytelling, authentic coastal milieu, and philosophical undertones about fate and human connections.', '2014-03-28', ARRAY['Anthology', 'Drama'], 'U', 'Kannada', 154, 'Rakshit Shetty', ARRAY['Rakshit Shetty', 'Sheetal Shetty'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/b7Ee4DKKhNVYNV84rovdqcWXjgt.jpg', NULL),
('Kirik Party', 'movie', 'A coming-of-age comedy-drama following a group of engineering students navigating friendship, love, and campus life. Rakshit Shetty''s breakout hit captures the essence of college nostalgia with its perfect blend of humor, romance, and emotional moments, becoming a cultural phenomenon among Karnataka''s youth.', '2016-12-30', ARRAY['Comedy', 'Drama'], 'U', 'Kannada', 159, 'Rishab Shetty', ARRAY['Rakshit Shetty', 'Rashmika Mandanna'], ARRAY['ZEE5'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/oKPrrCNGJuYdmn0ZeUZbPCAvvun.jpg', NULL);

-- Malayalam Movies (5 Famous Films)
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Drishyam', 'movie', 'A suspense thriller about a common man who constructs an elaborate alibi to protect his family after they accidentally commit a crime. Mohanlal delivers a masterclass in understated acting as the clever cable operator who outwits the police through meticulous planning and his love for crime films, creating an iconic Indian cinematic masterpiece.', '2013-12-19', ARRAY['Thriller', 'Drama'], 'U', 'Malayalam', 160, 'Jeethu Joseph', ARRAY['Mohanlal', 'Meena'], ARRAY['Amazon Prime'], 'https://youtu.be/AuuX2j14NBg', 'https://www.themoviedb.org/t/p/w1280/7d8GLneJkF81q1POdK7VUrjWafX.jpg', NULL),
('Premam', 'movie', 'A coming-of-age romantic drama following George David through three phases of his life and the women who shape his journey from adolescence to adulthood. Nivin Pauly''s charismatic performance and the film''s nostalgic treatment of young love made it a cultural phenomenon, with its songs and style influencing youth culture across South India.', '2015-05-29', ARRAY['Romance', 'Drama'], 'U', 'Malayalam', 156, 'Alphonse Puthren', ARRAY['Nivin Pauly', 'Sai Pallavi'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/81VGhJEMeCsWy7W3QDtl217SnTY.jpg', NULL),
('Bangalore Days', 'movie', 'The lives of three cousins - the rebellious Arjun, traditional Divya, and wheelchair-bound Kuttan - intersect in Bangalore as they navigate love, dreams, and personal growth. This urban youth drama became a pan-Indian hit for its relatable characters, vibrant storytelling, and heartfelt exploration of modern relationships and aspirations.', '2014-05-30', ARRAY['Drama', 'Comedy'], 'U', 'Malayalam', 171, 'Anjali Menon', ARRAY['Nivin Pauly', 'Nazriya Nazim'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/iFMyZw1DTGvZ8hPa0eTseSFiRT1.jpg', NULL),
('Maheshinte Prathikaaram', 'movie', 'A mild-mannered photographer''s life changes when he gets into an unexpected fight and vows not to wear slippers until he gets revenge. Fahadh Faasil shines in this quirky comedy-drama that beautifully captures rural Kerala''s essence while delivering a satisfying underdog story with heart and humor.', '2016-02-05', ARRAY['Comedy', 'Drama'], 'U', 'Malayalam', 120, 'Dileesh Pothan', ARRAY['Fahadh Faasil', 'Aparna Balamurali'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/hmK9QUWpOaSs1H7tarzlMNqT60H.jpg', NULL),
('Kumbalangi Nights', 'movie', 'A poetic drama about four brothers living in a dysfunctional household in the fishing village of Kumbalangi, whose lives are transformed by love and unexpected connections. The film''s sensitive portrayal of masculinity, mental health, and redemption features stunning visuals of backwater Kerala and career-defining performances from its ensemble cast.', '2019-02-07', ARRAY['Drama', 'Romance'], 'U', 'Malayalam', 135, 'Madhu C. Narayanan', ARRAY['Shane Nigam', 'Fahadh Faasil'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/o0Is0aKOhwhDoit7t3fyovifweO.jpg', NULL);

-- Tamil Movies (5 Famous Films)
INSERT INTO content (title, content_type, description, release_date, genre, age_rating, language, duration, director, "cast", streaming_info, trailer_url, poster_url, rating_avg) VALUES
('Ponniyin Selvan: Part 1', 'movie', 'Mani Ratnam''s epic historical adaptation of Kalki''s novel about the early life of Chola prince Arulmozhivarman. This visually magnificent period drama brings to life 10th century Chola empire politics with an all-star cast, intricate plotting, and breathtaking production design that captures the golden age of South Indian history.', '2022-09-30', ARRAY['Historical', 'Drama'], 'UA', 'Tamil', 167, 'Mani Ratnam', ARRAY['Vikram', 'Aishwarya Rai'], ARRAY['Amazon Prime'], 'https://youtu.be/KsH2LA8pCjo', 'https://www.themoviedb.org/t/p/w1280/zSNyZUeqDdii0doQ9970E90kCkb.jpg', NULL),
('Vikram', 'movie', 'A high-octane action thriller where a retired special agent comes out of hiding when his son is murdered, uncovering a dark conspiracy involving a shadowy squad of vigilantes. Kamal Haasan''s return to form features Lokesh Kanagaraj''s stylish direction, an electrifying background score, and unexpected connections to the wider LCU (Lokesh Cinematic Universe).', '2022-06-03', ARRAY['Action', 'Thriller'], 'UA', 'Tamil', 173, 'Lokesh Kanagaraj', ARRAY['Kamal Haasan', 'Vijay Sethupathi'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/OKBMCL-frPU', 'https://www.themoviedb.org/t/p/w1280/774UV1aCURb4s4JfEFg3IEMu5Zj.jpg', NULL),
('Super Deluxe', 'movie', 'An audacious anthology film following four dysfunctional stories that intersect in unexpected ways, exploring themes of sexuality, faith, and redemption. Thiagarajan Kumararaja''s genre-defying masterpiece features Vijay Sethupathi in a groundbreaking performance as a transgender woman, blending dark comedy with profound philosophical questions.', '2019-03-29', ARRAY['Anthology', 'Drama'], 'A', 'Tamil', 176, 'Thiagarajan Kumararaja', ARRAY['Vijay Sethupathi', 'Fahadh Faasil'], ARRAY['Netflix'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/6N346GcTUjhYa0InIiGHW61Zo3O.jpg', NULL),
('Kaithi', 'movie', 'A relentless action thriller about an ex-convict who helps police transport seized drugs while trying to reunite with his daughter. Karthi delivers a career-best performance in this single-night saga that combines breathtaking action sequences with emotional depth, establishing Lokesh Kanagaraj as Tamil cinema''s new action auteur.', '2019-10-25', ARRAY['Action', 'Thriller'], 'UA', 'Tamil', 145, 'Lokesh Kanagaraj', ARRAY['Karthi', 'Narain'], ARRAY['Disney+ Hotstar'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/s3VZHlvfU6Mg95Db2Q5Dkqy6gDY.jpg', NULL),
('96', 'movie', 'A poignant romance about childhood sweethearts who reunite after 22 years at a school reunion, confronting unresolved feelings and life''s missed opportunities. Vijay Sethupathi and Trisha''s chemistry elevates this nostalgic tearjerker that beautifully captures the bittersweet nature of first love and the passage of time.', '2018-10-04', ARRAY['Romance', 'Drama'], 'U', 'Tamil', 158, 'C. Prem Kumar', ARRAY['Vijay Sethupathi', 'Trisha'], ARRAY['Amazon Prime'], 'https://youtu.be/9w6LmLqVzVY', 'https://www.themoviedb.org/t/p/w1280/nrVloCa2hCFOztRF1DZU2jnWIiQ.jpg', NULL);
